site_name: 浙江大学本科新生指引
site_author: mini-full
site_description: 浙江大学本科生新生指引为浙江大学CC98论坛新生宝典版面编撰的新生入学指南。
repo_name: zju-welcome
repo_url: https://github.com/mini-full/zju-welcome/

copyright: Copyright &copy; 2023-present <a href="https://github.com/mini-full" target="_blank" rel="noopener noreferrer">minifull</a>


nav:
  - 首页: "index.md"
  - 前言:
    - 前言: "preface.md"
    - 作者声明: "statement2022.md"
    - 重要提示: "callout.md"
    - 导语: "intro.md"
  - CC98论坛攻略: "cc98.md"
  - 常用信息:
    - 浙大校历: "basics/school_calendar.md"
    - 校园地图: "basics/school_map.md"
    - 浙大文化:
      - 精神内核: "basics/school_spirits.md"
      - 竺老两问: "basics/2questions.md"
      - 浙大简史: "basics/history.md"
      - 浙大校歌: "basics/school_song.md"
    - 校区院系:
      - 浙大校区: "basics/campuses.md"
      - 学部院系: "basics/colleges.md"
    - 信息平台:
      - 常用电话: "basics/contact.md"
      - 常用网站: "basics/websites.md"
      - 公众号和小程序: "basics/channels.md"
    - 特色黑话: "basics/slang.md"
    - 校园网指南: "basics/network_guidance.md"
  - 入学:
    - 注册缴费: "registration/fee.md"
    - 物品准备: "registration/items_to_take.md"
    - 入校交通: "registration/transportation.md"
    - 报到流程: "registration/procedure.md"
    - 始业教育: "registration/initial_edu.md"
    - 新生防骗: "registration/secure.md"
  - 军训:
    - 作息时间: "military_training/time.md"
    - 组织架构: "military_training/structure.md"
    - 军训活动: "military_training/activities.md"
    - 入党专题: "military_training/party.md"
    - 其他事项: "military_training/others.md"
    - 温馨提醒: "military_training/reminder.md"
  - 学习:
    - 基本概念: "learning/concepts.md"
    - 培养方案: "learning/program.md"
    - 课程考核: "learning/eval.md"
    - 专业分流: "learning/declaring_major.md"
    - 转专业: "learning/major_transfer.md"
    - 特殊课程: "learning/special_course.md"
    - 训练计划: "learning/training_program.md"
    - 学科竞赛: "learning/competitions.md"
    - 竺院选拔: "learning/intoCKC.md"
    - 邮件系统与邮件礼仪: "learning/email_etiquette.md"
  - 选课:
    - 选课通知: "course_sys/enroll.md"
    - 选课规则: "course_sys/rules.md"
    - 概念解释: "course_sys/concepts.md"
    - 选课操作: "course_sys/operation.md"
    - 选课技巧: "course_sys/tricks.md"
  - 生活:
    - 校园区域: "life/campus.md"
    - 寝室园区: "life/dorm.md"
    - 收寄服务: "life/post.md"
    - 饮食消费: "life/canteen.md"
    - 学生组织与社团: "life/extracurricular.md"
    - 运动场馆与艺术中心: "life/sports.md"
    - 杭城掠影: "life/hangzhou.md"
  - 奖助:
    - 基础评价: "funding/evaluation.md"
    - 荣誉体系: "funding/honor.md"
    - 奖学金: "funding/scholarship.md"
    - 学生资助: "funding/financial_aid.md"

  
  - 海宁国际校区:
    - 概述: "haining/intro.md"
    - 常用信息:
      - 院历: "haining/basics/school_calendar.md"
      - 校区地图: "haining/basics/campus_map.md"
      - 常用电话: "haining/basics/contact.md"
      - 常用网站: "haining/basics/websites.md"
      - 公众号和小程序: "haining/basics/channels.md"
      - 校园网指南: "life/network.md"
      - 白嫖指南: "haining/basics/free.md"
    - 学习:
      - 名词解释: "haining/learning/concepts.md"
      - 培养方案: "haining/learning/program.md"
      - 课程考核: "haining/learning/eval.md"
      - 大一课程简介: "haining/learning/course_intro.md"
      - 通识课: "haining/learning/general_edu.md"
    - 评奖评优: "haining/scholarship.md"
    - 校园生活: 
      - 吃住: "haining/life/canteen_dorm.md"
      - 学生活动: "haining/life/extracurricular.md"
      - 社会实践: "haining/life/practice.md"

  - 港澳台生专题:
    - 身份证件: "HK_Macao_Taiwan/id.md"
    - 生活适应: "HK_Macao_Taiwan/livingatzju.md"
    - 课程衔接与要求: "HK_Macao_Taiwan/specialcourses.md"
    - 实践实习活动: "HK_Macao_Taiwan/practice.md"
    - 升学就业: "HK_Macao_Taiwan/post-graduation.md"
    - 认识祖国大好河山: "HK_Macao_Taiwan/traveling.md"

  - 后记:
    - 后记: "postscript.md"
    - 完稿小记: "postscript2022.md"
  

theme:
  name: material
  language: zh
  logo: assets/校徽_白.png
  custom_dir: overrides
  palette:
    # # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode
    #   primary: custom

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - toc.integrate
    - toc.follow
    - navigation.top
    - navigation.footer
    - navigation.expand

    - search.highlight
    - search.share
    - search.suggest


plugins:
  - search:
      lang:
        - zh
        - en
        - ja
      separator: '[\s\u200b\-]'


extra_css:
  - stylesheets/extra.css


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mini-full/zju-welcome
    - icon: material/forum
      link: https://www.cc98.org/topic/5672880
    - icon: fontawesome/solid/paper-plane
      link: mailto:kaixuanwang@zju.edu.cn
    - icon: simple/githubpages
      link: https://mini-full.github.io/zju-welcome/
    - icon: material/web-check
      link: https://zjuers.com/welcome/
    